In [6]:
import pandas as pd

In [7]:
from google.colab import files
uploaded = files.upload()

Saving student_performance.csv to student_performance (1).csv

In [8]:
df = pd.read_csv("student_performance.csv")

df.head()

,StudyHours,Attendance,Resources,Extracurricular,Motivation,Internet,Gender,Age,LearningStyle,OnlineCourses,Discussions,AssignmentCompletion,ExamScore,EduTech,StressLevel,FinalGrade
0,19,64,1,0,0,1,0,19,2,8,1,59,40,0,1,3
1,19,64,1,0,0,1,0,23,3,16,0,90,66,0,1,2
2,19,64,1,0,0,1,0,28,1,19,0,67,99,1,1,0
3,19,64,1,1,0,1,0,19,2,8,1,59,40,0,1,3
4,19,64,1,1,0,1,0,23,3,16,0,90,66,0,1,2

In [9]:
print(df.columns)

Index(['StudyHours', 'Attendance', 'Resources', 'Extracurricular',
       'Motivation', 'Internet', 'Gender', 'Age', 'LearningStyle',
       'OnlineCourses', 'Discussions', 'AssignmentCompletion', 'ExamScore',
       'EduTech', 'StressLevel', 'FinalGrade'],
      dtype='object')

In [10]:
print(df.shape)

(14003, 16)

In [11]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14003 entries, 0 to 14002
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudyHours            14003 non-null  int64
 1   Attendance            14003 non-null  int64
 2   Resources             14003 non-null  int64
 3   Extracurricular       14003 non-null  int64
 4   Motivation            14003 non-null  int64
 5   Internet              14003 non-null  int64
 6   Gender                14003 non-null  int64
 7   Age                   14003 non-null  int64
 8   LearningStyle         14003 non-null  int64
 9   OnlineCourses         14003 non-null  int64
 10  Discussions           14003 non-null  int64
 11  AssignmentCompletion  14003 non-null  int64
 12  ExamScore             14003 non-null  int64
 13  EduTech               14003 non-null  int64
 14  StressLevel           14003 non-null  int64
 15  FinalGrade            14003 non-null  int64
dtypes: int64(16)
memory usage: 1.7 MB
None

In [12]:
df.isnull()

,StudyHours,Attendance,Resources,Extracurricular,Motivation,Internet,Gender,Age,LearningStyle,OnlineCourses,Discussions,AssignmentCompletion,ExamScore,EduTech,StressLevel,FinalGrade
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14001,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14002,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

StudyHours              0
Attendance              0
Resources               0
Extracurricular         0
Motivation              0
Internet                0
Gender                  0
Age                     0
LearningStyle           0
OnlineCourses           0
Discussions             0
AssignmentCompletion    0
ExamScore               0
EduTech                 0
StressLevel             0
FinalGrade              0
dtype: int64

In [14]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['studyhours', 'attendance', 'resources', 'extracurricular',
       'motivation', 'internet', 'gender', 'age', 'learningstyle',
       'onlinecourses', 'discussions', 'assignmentcompletion', 'examscore',
       'edutech', 'stresslevel', 'finalgrade'],
      dtype='object')

In [15]:
df.duplicated().sum()

np.int64(1534)

In [16]:
df= df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [17]:
df = df.reset_index(drop=True)

In [18]:
def performance_category(score):
  if score>=85:
    return"Excellent!"
  elif score>=70:
    return"Good"
  elif score>=50:
    return "Average"
  else:
    return "Poor"
df['performance'] = df['examscore'].apply(performance_category)

In [19]:
def assign_grade(score):
  if score>=90:
    return "A+"
  elif score>=80:
    return "A"
  elif score>=70:
    return "B"
  elif score>=60:
    return "C"
  elif score>=50:
    return "D"
  else:
    return "F"
  df['grade'] = df['examscore'].apply(assign_grade)

In [20]:
df[['examscore', 'performance', 'grade']]

KeyError: "['grade'] not in index"

In [ ]:
print(df.columns)

In [ ]:
df['grade'] = df['examscore'].apply(assign_grade)

In [ ]:
def generate_insight(row):
    insights = []

    if row['attendance'] < 60:
        insights.append("Low attendance may affect performance")

    if row['studyhours'] < 2:
        insights.append("Low study hours")

    if row['stresslevel'] > 7:
        insights.append("High stress impacting performance")

    if row['assignmentcompletion'] < 50:
        insights.append("Assignments not completed properly")

    if row['examscore'] > 85:
        insights.append("Excellent academic performance")

    if row['examscore'] < 50:
        insights.append("Needs improvement in academics")

    # Default case
    if len(insights) == 0:
        return "Stable performance with no major issues"

    return ", ".join(insights)

In [ ]:
df['insight'] = df.apply(generate_insight, axis=1)

In [ ]:
df[['examscore','performance','grade','studyhours','insight']]

In [ ]:
df.groupby('attendance')['examscore'].mean().head(10)

In [ ]:
df.groupby('studyhours')['examscore'].mean()

In [ ]:
df.groupby('stresslevel')['examscore'].mean()

In [ ]:
import matplotlib.pyplot as plt

df.groupby('attendance')['examscore'].mean().plot()
plt.title("Attendance vs Exam Score")
plt.xlabel("Attendance")
plt.ylabel("Average Exam Score")
plt.show()

In [ ]:
df.groupby('studyhours')['examscore'].mean().plot()
plt.title("Study Hours vs Exam Score")
plt.xlabel("Study Hours")
plt.ylabel("Average Exam Score")
plt.show()

In [ ]:
df.groupby('stresslevel')['examscore'].mean().plot()
plt.title("Stress Level vs Exam Score")
plt.xlabel("Stress Level")
plt.ylabel("Average Exam Score")
plt.show()

In [ ]:
X = df[['studyhours', 'attendance', 'motivation', 'assignmentcompletion']]

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

In [ ]:
df.corr(numeric_only=True)['examscore'].sort_values(ascending=False)